export const PURCHASE_ORDER_STATUS = {
  OPEN: "Open",
  APPROVED: "Approved",
  COMPLETED: "Completed",
};

export const ALL_STATUS_FILTER = "All";

export const PAGE_SIZE_OPTIONS = [5, 10, 20];

export const STATUS_TRANSITIONS = {
  [PURCHASE_ORDER_STATUS.OPEN]: [
    PURCHASE_ORDER_STATUS.OPEN,
    PURCHASE_ORDER_STATUS.APPROVED,
  ],
  [PURCHASE_ORDER_STATUS.APPROVED]: [
    PURCHASE_ORDER_STATUS.APPROVED,
    PURCHASE_ORDER_STATUS.COMPLETED,
  ],
  [PURCHASE_ORDER_STATUS.COMPLETED]: [PURCHASE_ORDER_STATUS.COMPLETED],
};
